#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#Load modules
module load eb
module load Miniconda2
#loading virtualenv
source activate qiime1
#setting temporary directory
export TMDIR=~/qiime_tmp
echo “core diversity analyses”
time core_diversity_analyses.py -i ~/2018_02_smb/OTUS2018/otu_table.biom -o ~/2018_02_smb/core_output_2018 -t ~/SILVA_128_QIIME_release/trees/97/97_otus.tre -m ~/2018_02_smb/map.tsv -e 605
source deactivate qiime1
